### ISSUE TITLE
Match of length 5 not found by MMC algorithm

### ISSUE THREAD

**Issue by maestrosoft** [Cyan4973/mmc#2] opened 2022-08-02 20:14 UTC
Unless I missed something and misunderstood the algorithm, I believe there is an issue in the code. I have tried a simple example and cannot find the same matches as the software code. For example, if you use this string sequence as input:

abcd0zt%$abcd1?dfgabcd2poiuabcd0;tr/!abcd0z%1&*abcd8bre~dabcd2zt+=:_abcd8br)abcd8be&abcd8bc#abcd8bea%$abcd0z+#@!s#

The code provides those matches 

pos     9: found match of length  4 (abcd)
pos    18: found match of length  4 (abcd)
pos    27: found match of length  5 (abcd0)
pos    28: found match of length  4 (bcd0)
pos    37: found match of length  6 (abcd0z)
pos    38: found match of length  5 (bcd0z)
pos    39: found match of length  4 (cd0z)
pos    47: found match of length  4 (abcd)
pos    57: found match of length  4 (abcd) --> expected abcd2 of length 5
pos    58: found match of length  4 (bcd2)
(…)

**Comment by Cyan4973** [comment] 2022-08-03 21:10
I haven't looked at the code in a long time, and I have a vague remembrance that last time I did (several years back), there were some unidentified problems, that I had no time to investigate.
So reports sounds most likely true to me.

The problem is really finding available time.

**Comment by Cyan4973** [comment] 2022-08-03 21:40
I updated the `example` program to visualize the found matches, like in your example, and I can confirm the issue : position 57 should have found a match of length 5 at position 18.

**Comment by Cyan4973** [comment] 2022-08-03 23:19
I updated `mmc` by re-employing an older version of the main function.
It seems to work fine with your example, and can detect the wanted match of length 5 at position 57.

**Comment by Cyan4973** [comment] 2022-08-08 23:07
fix merged

**Closed by Cyan4973** 2022-08-08 23:07 UTC
Labels: bug
